import '../less/index.less';
import main from './handel';
import audio from './musicOn';
import first from './firstView';
import last from './lastView';
import '../images/audio.mp3';
main();
first();
last();
audio();
